// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors
// SPDX-FileCopyrightText: 2026 Unicode, Inc.
//
// Sentence-break data is derived from Unicode 18.0.0.
// See the Unicode section in THIRD_PARTY_LICENSES.md for its license.

// Code generated by gen.go; DO NOT EDIT.

package chunk

// isATerm reports whether r is in UAX #29's Sentence_Break = ATerm class.
func isATerm(r rune) bool {
	switch r {
	case 0x002E: // FULL STOP
		return true
	case 0x2024: // ONE DOT LEADER
		return true
	case 0xFE52: // SMALL FULL STOP
		return true
	case 0xFF0E: // FULLWIDTH FULL STOP
		return true
	}
	return false
}
