// Code generated by file2byteslice. DO NOT EDIT.
// (gofmt is fine after generating)

package main

var program_cs = []byte("\ufeffusing System;\nusing {{.Namespace}}.AutoGen;\n\nnamespace {{.Namespace}}\n{\n    public static class Program\n    {\n        [STAThread]\n        static void Main()\n        {\n            Go go = new Go();\n            go.Run();\n        }\n    }\n}\n")
