// Code generated by file2byteslice. DO NOT EDIT.
// (gofmt is fine after generating)

package main

var project_csproj = []byte("<Project Sdk=\"Microsoft.NET.Sdk\">\n\n  <PropertyGroup>\n    <OutputType>WinExe</OutputType>\n    <TargetFramework>net48</TargetFramework>\n  </PropertyGroup>\n\n  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \">\n    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n  </PropertyGroup>\n  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \">\n    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>\n  </PropertyGroup>\n\n  <ItemGroup>\n    <MonoGameContentReference Include=\"**\\*.mgcb\" />\n  </ItemGroup>\n\n  <ItemGroup>\n    <PackageReference Include=\"MonoGame.Content.Builder\" Version=\"3.7.0.9\" />\n    <PackageReference Include=\"MonoGame.Framework.DesktopGL.Core\" Version=\"3.8.0.13\" />\n  </ItemGroup>\n\n</Project>\n")
