// Copyright 2013 The Ebiten Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by genkeys.go using 'go generate'. DO NOT EDIT.

package event

import (
	"github.com/hajimehoshi/ebiten/internal/driver"
)

type Key = driver.Key

const (
	Key0            = driver.Key0
	Key1            = driver.Key1
	Key2            = driver.Key2
	Key3            = driver.Key3
	Key4            = driver.Key4
	Key5            = driver.Key5
	Key6            = driver.Key6
	Key7            = driver.Key7
	Key8            = driver.Key8
	Key9            = driver.Key9
	KeyA            = driver.KeyA
	KeyB            = driver.KeyB
	KeyC            = driver.KeyC
	KeyD            = driver.KeyD
	KeyE            = driver.KeyE
	KeyF            = driver.KeyF
	KeyG            = driver.KeyG
	KeyH            = driver.KeyH
	KeyI            = driver.KeyI
	KeyJ            = driver.KeyJ
	KeyK            = driver.KeyK
	KeyL            = driver.KeyL
	KeyM            = driver.KeyM
	KeyN            = driver.KeyN
	KeyO            = driver.KeyO
	KeyP            = driver.KeyP
	KeyQ            = driver.KeyQ
	KeyR            = driver.KeyR
	KeyS            = driver.KeyS
	KeyT            = driver.KeyT
	KeyU            = driver.KeyU
	KeyV            = driver.KeyV
	KeyW            = driver.KeyW
	KeyX            = driver.KeyX
	KeyY            = driver.KeyY
	KeyZ            = driver.KeyZ
	KeyApostrophe   = driver.KeyApostrophe
	KeyBackslash    = driver.KeyBackslash
	KeyBackspace    = driver.KeyBackspace
	KeyCapsLock     = driver.KeyCapsLock
	KeyComma        = driver.KeyComma
	KeyDelete       = driver.KeyDelete
	KeyDown         = driver.KeyDown
	KeyEnd          = driver.KeyEnd
	KeyEnter        = driver.KeyEnter
	KeyEqual        = driver.KeyEqual
	KeyEscape       = driver.KeyEscape
	KeyF1           = driver.KeyF1
	KeyF2           = driver.KeyF2
	KeyF3           = driver.KeyF3
	KeyF4           = driver.KeyF4
	KeyF5           = driver.KeyF5
	KeyF6           = driver.KeyF6
	KeyF7           = driver.KeyF7
	KeyF8           = driver.KeyF8
	KeyF9           = driver.KeyF9
	KeyF10          = driver.KeyF10
	KeyF11          = driver.KeyF11
	KeyF12          = driver.KeyF12
	KeyGraveAccent  = driver.KeyGraveAccent
	KeyHome         = driver.KeyHome
	KeyInsert       = driver.KeyInsert
	KeyKP0          = driver.KeyKP0
	KeyKP1          = driver.KeyKP1
	KeyKP2          = driver.KeyKP2
	KeyKP3          = driver.KeyKP3
	KeyKP4          = driver.KeyKP4
	KeyKP5          = driver.KeyKP5
	KeyKP6          = driver.KeyKP6
	KeyKP7          = driver.KeyKP7
	KeyKP8          = driver.KeyKP8
	KeyKP9          = driver.KeyKP9
	KeyKPAdd        = driver.KeyKPAdd
	KeyKPDecimal    = driver.KeyKPDecimal
	KeyKPDivide     = driver.KeyKPDivide
	KeyKPEnter      = driver.KeyKPEnter
	KeyKPEqual      = driver.KeyKPEqual
	KeyKPMultiply   = driver.KeyKPMultiply
	KeyKPSubtract   = driver.KeyKPSubtract
	KeyLeft         = driver.KeyLeft
	KeyLeftAlt      = driver.KeyLeftAlt
	KeyLeftBracket  = driver.KeyLeftBracket
	KeyLeftControl  = driver.KeyLeftControl
	KeyLeftShift    = driver.KeyLeftShift
	KeyMenu         = driver.KeyMenu
	KeyMinus        = driver.KeyMinus
	KeyNumLock      = driver.KeyNumLock
	KeyPageDown     = driver.KeyPageDown
	KeyPageUp       = driver.KeyPageUp
	KeyPause        = driver.KeyPause
	KeyPeriod       = driver.KeyPeriod
	KeyPrintScreen  = driver.KeyPrintScreen
	KeyRight        = driver.KeyRight
	KeyRightAlt     = driver.KeyRightAlt
	KeyRightBracket = driver.KeyRightBracket
	KeyRightControl = driver.KeyRightControl
	KeyRightShift   = driver.KeyRightShift
	KeyScrollLock   = driver.KeyScrollLock
	KeySemicolon    = driver.KeySemicolon
	KeySlash        = driver.KeySlash
	KeySpace        = driver.KeySpace
	KeyTab          = driver.KeyTab
	KeyUp           = driver.KeyUp
)
