// Copyright 2026 The Ebitengine Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"embed"
	"path/filepath"
	"strings"

	"github.com/hajimehoshi/ebiten/v2/exp/shaderprecomp"
)

// shaderFiles holds the shaders generated by 'go generate'. dummy.txt is a
// placeholder that keeps the //go:embed directive valid before they exist.
//
//go:embed shaders
var shaderFiles embed.FS

func init() {
	type glslSources struct {
		vertex     []byte
		fragment   []byte
		esVertex   []byte
		esFragment []byte
	}
	type fxcBinaries struct {
		vertex []byte
		pixel  []byte
	}
	type metalLibraries struct {
		macOS []byte
		iOS   []byte
	}

	// The files are named "<id>_<kind>.<ext>". A source ID is base32 and never
	// contains '_', so the part before the first '_' is the ID.
	glsls := map[string]*glslSources{}
	fxcs := map[string]*fxcBinaries{}
	metallibs := map[string]*metalLibraries{}

	entries, err := shaderFiles.ReadDir("shaders")
	if err != nil {
		panic(err)
	}
	for _, entry := range entries {
		name := entry.Name()
		ext := filepath.Ext(name)
		stem := strings.TrimSuffix(name, ext)
		switch ext {
		case ".glsl":
			id, kind, ok := strings.Cut(stem, "_")
			if !ok {
				continue
			}
			s := glsls[id]
			if s == nil {
				s = &glslSources{}
				glsls[id] = s
			}
			switch kind {
			case "vertex":
				s.vertex = readShaderFile(name)
			case "fragment":
				s.fragment = readShaderFile(name)
			case "es_vertex":
				s.esVertex = readShaderFile(name)
			case "es_fragment":
				s.esFragment = readShaderFile(name)
			}

		case ".fxc":
			id, kind, ok := strings.Cut(stem, "_")
			if !ok {
				continue
			}
			b := fxcs[id]
			if b == nil {
				b = &fxcBinaries{}
				fxcs[id] = b
			}
			switch kind {
			case "vertex":
				b.vertex = readShaderFile(name)
			case "pixel":
				b.pixel = readShaderFile(name)
			}

		case ".metallib":
			id, kind, ok := strings.Cut(stem, "_")
			if !ok {
				continue
			}
			m := metallibs[id]
			if m == nil {
				m = &metalLibraries{}
				metallibs[id] = m
			}
			switch kind {
			case "macos":
				m.macOS = readShaderFile(name)
			case "ios":
				m.iOS = readShaderFile(name)
			}
		}
	}

	for id, s := range glsls {
		shaderprecomp.RegisterGLSL(shaderprecomp.MustParseShaderSourceID(id), s.vertex, s.fragment, s.esVertex, s.esFragment)
		precompiledShadersRegistered = true
	}
	for id, b := range fxcs {
		shaderprecomp.RegisterFXCs(shaderprecomp.MustParseShaderSourceID(id), b.vertex, b.pixel)
		precompiledShadersRegistered = true
	}
	for id, m := range metallibs {
		pid := shaderprecomp.MustParseShaderSourceID(id)
		if m.macOS != nil {
			shaderprecomp.RegisterMetalLibraryForMacOS(pid, m.macOS)
			precompiledShadersRegistered = true
		}
		if m.iOS != nil {
			shaderprecomp.RegisterMetalLibraryForIOS(pid, m.iOS)
			precompiledShadersRegistered = true
		}
	}
}

// readShaderFile returns the contents of the named file in the shaders directory.
func readShaderFile(name string) []byte {
	content, err := shaderFiles.ReadFile("shaders/" + name)
	if err != nil {
		panic(err)
	}
	return content
}
