// Copyright 2013 The Ebiten Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by genkeys.go using 'go generate'. DO NOT EDIT.

// +build darwin freebsd linux windows
// +build !js
// +build !android
// +build !ios

package input

import (
	"github.com/hajimehoshi/ebiten/internal/glfw"
)

var glfwKeyCodeToKey = map[glfw.Key]Key{
	glfw.Key0:            Key0,
	glfw.Key1:            Key1,
	glfw.Key2:            Key2,
	glfw.Key3:            Key3,
	glfw.Key4:            Key4,
	glfw.Key5:            Key5,
	glfw.Key6:            Key6,
	glfw.Key7:            Key7,
	glfw.Key8:            Key8,
	glfw.Key9:            Key9,
	glfw.KeyA:            KeyA,
	glfw.KeyB:            KeyB,
	glfw.KeyC:            KeyC,
	glfw.KeyD:            KeyD,
	glfw.KeyE:            KeyE,
	glfw.KeyF:            KeyF,
	glfw.KeyG:            KeyG,
	glfw.KeyH:            KeyH,
	glfw.KeyI:            KeyI,
	glfw.KeyJ:            KeyJ,
	glfw.KeyK:            KeyK,
	glfw.KeyL:            KeyL,
	glfw.KeyM:            KeyM,
	glfw.KeyN:            KeyN,
	glfw.KeyO:            KeyO,
	glfw.KeyP:            KeyP,
	glfw.KeyQ:            KeyQ,
	glfw.KeyR:            KeyR,
	glfw.KeyS:            KeyS,
	glfw.KeyT:            KeyT,
	glfw.KeyU:            KeyU,
	glfw.KeyV:            KeyV,
	glfw.KeyW:            KeyW,
	glfw.KeyX:            KeyX,
	glfw.KeyY:            KeyY,
	glfw.KeyZ:            KeyZ,
	glfw.KeyApostrophe:   KeyApostrophe,
	glfw.KeyBackslash:    KeyBackslash,
	glfw.KeyBackspace:    KeyBackspace,
	glfw.KeyCapsLock:     KeyCapsLock,
	glfw.KeyComma:        KeyComma,
	glfw.KeyDelete:       KeyDelete,
	glfw.KeyDown:         KeyDown,
	glfw.KeyEnd:          KeyEnd,
	glfw.KeyEnter:        KeyEnter,
	glfw.KeyEqual:        KeyEqual,
	glfw.KeyEscape:       KeyEscape,
	glfw.KeyF1:           KeyF1,
	glfw.KeyF2:           KeyF2,
	glfw.KeyF3:           KeyF3,
	glfw.KeyF4:           KeyF4,
	glfw.KeyF5:           KeyF5,
	glfw.KeyF6:           KeyF6,
	glfw.KeyF7:           KeyF7,
	glfw.KeyF8:           KeyF8,
	glfw.KeyF9:           KeyF9,
	glfw.KeyF10:          KeyF10,
	glfw.KeyF11:          KeyF11,
	glfw.KeyF12:          KeyF12,
	glfw.KeyGraveAccent:  KeyGraveAccent,
	glfw.KeyHome:         KeyHome,
	glfw.KeyInsert:       KeyInsert,
	glfw.KeyKP0:          KeyKP0,
	glfw.KeyKP1:          KeyKP1,
	glfw.KeyKP2:          KeyKP2,
	glfw.KeyKP3:          KeyKP3,
	glfw.KeyKP4:          KeyKP4,
	glfw.KeyKP5:          KeyKP5,
	glfw.KeyKP6:          KeyKP6,
	glfw.KeyKP7:          KeyKP7,
	glfw.KeyKP8:          KeyKP8,
	glfw.KeyKP9:          KeyKP9,
	glfw.KeyKPAdd:        KeyKPAdd,
	glfw.KeyKPDecimal:    KeyKPDecimal,
	glfw.KeyKPDivide:     KeyKPDivide,
	glfw.KeyKPEnter:      KeyKPEnter,
	glfw.KeyKPEqual:      KeyKPEqual,
	glfw.KeyKPMultiply:   KeyKPMultiply,
	glfw.KeyKPSubtract:   KeyKPSubtract,
	glfw.KeyLeft:         KeyLeft,
	glfw.KeyLeftBracket:  KeyLeftBracket,
	glfw.KeyMenu:         KeyMenu,
	glfw.KeyMinus:        KeyMinus,
	glfw.KeyNumLock:      KeyNumLock,
	glfw.KeyPageDown:     KeyPageDown,
	glfw.KeyPageUp:       KeyPageUp,
	glfw.KeyPause:        KeyPause,
	glfw.KeyPeriod:       KeyPeriod,
	glfw.KeyPrintScreen:  KeyPrintScreen,
	glfw.KeyRight:        KeyRight,
	glfw.KeyRightBracket: KeyRightBracket,
	glfw.KeyScrollLock:   KeyScrollLock,
	glfw.KeySemicolon:    KeySemicolon,
	glfw.KeySlash:        KeySlash,
	glfw.KeySpace:        KeySpace,
	glfw.KeyTab:          KeyTab,
	glfw.KeyUp:           KeyUp,

	glfw.KeyLeftAlt:      KeyAlt,
	glfw.KeyRightAlt:     KeyAlt,
	glfw.KeyLeftControl:  KeyControl,
	glfw.KeyRightControl: KeyControl,
	glfw.KeyLeftShift:    KeyShift,
	glfw.KeyRightShift:   KeyShift,
}
