// Copyright 2013 The Ebiten Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT: This file is auto-generated by genkeys.go.

// +build js

package ui

var keyCodeToKey = map[string]Key{
	"AltLeft":      KeyAlt,
	"AltRight":     KeyAlt,
	"ArrowDown":    KeyDown,
	"ArrowLeft":    KeyLeft,
	"ArrowRight":   KeyRight,
	"ArrowUp":      KeyUp,
	"Backspace":    KeyBackspace,
	"CapsLock":     KeyCapsLock,
	"Comma":        KeyComma,
	"ControlLeft":  KeyControl,
	"ControlRight": KeyControl,
	"Delete":       KeyDelete,
	"Digit0":       Key0,
	"Digit1":       Key1,
	"Digit2":       Key2,
	"Digit3":       Key3,
	"Digit4":       Key4,
	"Digit5":       Key5,
	"Digit6":       Key6,
	"Digit7":       Key7,
	"Digit8":       Key8,
	"Digit9":       Key9,
	"End":          KeyEnd,
	"Enter":        KeyEnter,
	"Escape":       KeyEscape,
	"F1":           KeyF1,
	"F10":          KeyF10,
	"F11":          KeyF11,
	"F12":          KeyF12,
	"F2":           KeyF2,
	"F3":           KeyF3,
	"F4":           KeyF4,
	"F5":           KeyF5,
	"F6":           KeyF6,
	"F7":           KeyF7,
	"F8":           KeyF8,
	"F9":           KeyF9,
	"Home":         KeyHome,
	"Insert":       KeyInsert,
	"KeyA":         KeyA,
	"KeyB":         KeyB,
	"KeyC":         KeyC,
	"KeyD":         KeyD,
	"KeyE":         KeyE,
	"KeyF":         KeyF,
	"KeyG":         KeyG,
	"KeyH":         KeyH,
	"KeyI":         KeyI,
	"KeyJ":         KeyJ,
	"KeyK":         KeyK,
	"KeyL":         KeyL,
	"KeyM":         KeyM,
	"KeyN":         KeyN,
	"KeyO":         KeyO,
	"KeyP":         KeyP,
	"KeyQ":         KeyQ,
	"KeyR":         KeyR,
	"KeyS":         KeyS,
	"KeyT":         KeyT,
	"KeyU":         KeyU,
	"KeyV":         KeyV,
	"KeyW":         KeyW,
	"KeyX":         KeyX,
	"KeyY":         KeyY,
	"KeyZ":         KeyZ,
	"PageDown":     KeyPageDown,
	"PageUp":       KeyPageUp,
	"Period":       KeyPeriod,
	"ShiftLeft":    KeyShift,
	"ShiftRight":   KeyShift,
	"Space":        KeySpace,
	"Tab":          KeyTab,
}
