// Copyright 2013 The Ebiten Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by genkeys.go using 'go generate'. DO NOT EDIT.

package ui

import (
	"fmt"
)

type MidiReader interface {
	Read() error
	Close() error

	GetMidiKey(m uint8) bool
}

type MidiKey uint8

const (
	NoteC_1      MidiKey = 0
	NoteCSharp_1 MidiKey = 1
	NoteDFlat_1  MidiKey = 1
	NoteD_1      MidiKey = 2
	NoteDSharp_1 MidiKey = 3
	NoteEFlat_1  MidiKey = 3
	NoteE_1      MidiKey = 4
	NoteF_1      MidiKey = 5
	NoteFSharp_1 MidiKey = 6
	NoteGFlat_1  MidiKey = 6
	NoteG_1      MidiKey = 7
	NoteGSharp_1 MidiKey = 8
	NoteAFlat_1  MidiKey = 8
	NoteA_1      MidiKey = 9
	NoteASharp_1 MidiKey = 10
	NoteBFlat_1  MidiKey = 10
	NoteB_1      MidiKey = 11
	NoteC0       MidiKey = 12
	NoteCSharp0  MidiKey = 13
	NoteDFlat0   MidiKey = 13
	NoteD0       MidiKey = 14
	NoteDSharp0  MidiKey = 15
	NoteEFlat0   MidiKey = 15
	NoteE0       MidiKey = 16
	NoteF0       MidiKey = 17
	NoteFSharp0  MidiKey = 18
	NoteGFlat0   MidiKey = 18
	NoteG0       MidiKey = 19
	NoteGSharp0  MidiKey = 20
	NoteAFlat0   MidiKey = 20
	NoteA0       MidiKey = 21
	NoteASharp0  MidiKey = 22
	NoteBFlat0   MidiKey = 22
	NoteB0       MidiKey = 23
	NoteC1       MidiKey = 24
	NoteCSharp1  MidiKey = 25
	NoteDFlat1   MidiKey = 25
	NoteD1       MidiKey = 26
	NoteDSharp1  MidiKey = 27
	NoteEFlat1   MidiKey = 27
	NoteE1       MidiKey = 28
	NoteF1       MidiKey = 29
	NoteFSharp1  MidiKey = 30
	NoteGFlat1   MidiKey = 30
	NoteG1       MidiKey = 31
	NoteGSharp1  MidiKey = 32
	NoteAFlat1   MidiKey = 32
	NoteA1       MidiKey = 33
	NoteASharp1  MidiKey = 34
	NoteBFlat1   MidiKey = 34
	NoteB1       MidiKey = 35
	NoteC2       MidiKey = 36
	NoteCSharp2  MidiKey = 37
	NoteDFlat2   MidiKey = 37
	NoteD2       MidiKey = 38
	NoteDSharp2  MidiKey = 39
	NoteEFlat2   MidiKey = 39
	NoteE2       MidiKey = 40
	NoteF2       MidiKey = 41
	NoteFSharp2  MidiKey = 42
	NoteGFlat2   MidiKey = 42
	NoteG2       MidiKey = 43
	NoteGSharp2  MidiKey = 44
	NoteAFlat2   MidiKey = 44
	NoteA2       MidiKey = 45
	NoteASharp2  MidiKey = 46
	NoteBFlat2   MidiKey = 46
	NoteB2       MidiKey = 47
	NoteC3       MidiKey = 48
	NoteCSharp3  MidiKey = 49
	NoteDFlat3   MidiKey = 49
	NoteD3       MidiKey = 50
	NoteDSharp3  MidiKey = 51
	NoteEFlat3   MidiKey = 51
	NoteE3       MidiKey = 52
	NoteF3       MidiKey = 53
	NoteFSharp3  MidiKey = 54
	NoteGFlat3   MidiKey = 54
	NoteG3       MidiKey = 55
	NoteGSharp3  MidiKey = 56
	NoteAFlat3   MidiKey = 56
	NoteA3       MidiKey = 57
	NoteASharp3  MidiKey = 58
	NoteBFlat3   MidiKey = 58
	NoteB3       MidiKey = 59
	NoteC4       MidiKey = 60
	NoteCSharp4  MidiKey = 61
	NoteDFlat4   MidiKey = 61
	NoteD4       MidiKey = 62
	NoteDSharp4  MidiKey = 63
	NoteEFlat4   MidiKey = 63
	NoteE4       MidiKey = 64
	NoteF4       MidiKey = 65
	NoteFSharp4  MidiKey = 66
	NoteGFlat4   MidiKey = 66
	NoteG4       MidiKey = 67
	NoteGSharp4  MidiKey = 68
	NoteAFlat4   MidiKey = 68
	NoteA4       MidiKey = 69
	NoteASharp4  MidiKey = 70
	NoteBFlat4   MidiKey = 70
	NoteB4       MidiKey = 71
	NoteC5       MidiKey = 72
	NoteCSharp5  MidiKey = 73
	NoteDFlat5   MidiKey = 73
	NoteD5       MidiKey = 74
	NoteDSharp5  MidiKey = 75
	NoteEFlat5   MidiKey = 75
	NoteE5       MidiKey = 76
	NoteF5       MidiKey = 77
	NoteFSharp5  MidiKey = 78
	NoteGFlat5   MidiKey = 78
	NoteG5       MidiKey = 79
	NoteGSharp5  MidiKey = 80
	NoteAFlat5   MidiKey = 80
	NoteA5       MidiKey = 81
	NoteASharp5  MidiKey = 82
	NoteBFlat5   MidiKey = 82
	NoteB5       MidiKey = 83
	NoteC6       MidiKey = 84
	NoteCSharp6  MidiKey = 85
	NoteDFlat6   MidiKey = 85
	NoteD6       MidiKey = 86
	NoteDSharp6  MidiKey = 87
	NoteEFlat6   MidiKey = 87
	NoteE6       MidiKey = 88
	NoteF6       MidiKey = 89
	NoteFSharp6  MidiKey = 90
	NoteGFlat6   MidiKey = 90
	NoteG6       MidiKey = 91
	NoteGSharp6  MidiKey = 92
	NoteAFlat6   MidiKey = 92
	NoteA6       MidiKey = 93
	NoteASharp6  MidiKey = 94
	NoteBFlat6   MidiKey = 94
	NoteB6       MidiKey = 95
	NoteC7       MidiKey = 96
	NoteCSharp7  MidiKey = 97
	NoteDFlat7   MidiKey = 97
	NoteD7       MidiKey = 98
	NoteDSharp7  MidiKey = 99
	NoteEFlat7   MidiKey = 99
	NoteE7       MidiKey = 100
	NoteF7       MidiKey = 101
	NoteFSharp7  MidiKey = 102
	NoteGFlat7   MidiKey = 102
	NoteG7       MidiKey = 103
	NoteGSharp7  MidiKey = 104
	NoteAFlat7   MidiKey = 104
	NoteA7       MidiKey = 105
	NoteASharp7  MidiKey = 106
	NoteBFlat7   MidiKey = 106
	NoteB7       MidiKey = 107
	NoteC8       MidiKey = 108
	NoteCSharp8  MidiKey = 109
	NoteDFlat8   MidiKey = 109
	NoteD8       MidiKey = 110
	NoteDSharp8  MidiKey = 111
	NoteEFlat8   MidiKey = 111
	NoteE8       MidiKey = 112
	NoteF8       MidiKey = 113
	NoteFSharp8  MidiKey = 114
	NoteGFlat8   MidiKey = 114
	NoteG8       MidiKey = 115
	NoteGSharp8  MidiKey = 116
	NoteAFlat8   MidiKey = 116
	NoteA8       MidiKey = 117
	NoteASharp8  MidiKey = 118
	NoteBFlat8   MidiKey = 118
	NoteB8       MidiKey = 119
	NoteC9       MidiKey = 120
	NoteCSharp9  MidiKey = 121
	NoteDFlat9   MidiKey = 121
	NoteD9       MidiKey = 122
	NoteDSharp9  MidiKey = 123
	NoteEFlat9   MidiKey = 123
	NoteE9       MidiKey = 124
	NoteF9       MidiKey = 125
	NoteFSharp9  MidiKey = 126
	NoteGFlat9   MidiKey = 126
	NoteG9       MidiKey = 127
)

var (
	midiNoteValueToMidiKey = [][]MidiKey{
		0:   {NoteC_1},
		1:   {NoteCSharp_1, NoteDFlat_1},
		2:   {NoteD_1},
		3:   {NoteDSharp_1, NoteEFlat_1},
		4:   {NoteE_1},
		5:   {NoteF_1},
		6:   {NoteFSharp_1, NoteGFlat_1},
		7:   {NoteG_1},
		8:   {NoteGSharp_1, NoteAFlat_1},
		9:   {NoteA_1},
		10:  {NoteASharp_1, NoteBFlat_1},
		11:  {NoteB_1},
		12:  {NoteC0},
		13:  {NoteCSharp0, NoteDFlat0},
		14:  {NoteD0},
		15:  {NoteDSharp0, NoteEFlat0},
		16:  {NoteE0},
		17:  {NoteF0},
		18:  {NoteFSharp0, NoteGFlat0},
		19:  {NoteG0},
		20:  {NoteGSharp0, NoteAFlat0},
		21:  {NoteA0},
		22:  {NoteASharp0, NoteBFlat0},
		23:  {NoteB0},
		24:  {NoteC1},
		25:  {NoteCSharp1, NoteDFlat1},
		26:  {NoteD1},
		27:  {NoteDSharp1, NoteEFlat1},
		28:  {NoteE1},
		29:  {NoteF1},
		30:  {NoteFSharp1, NoteGFlat1},
		31:  {NoteG1},
		32:  {NoteGSharp1, NoteAFlat1},
		33:  {NoteA1},
		34:  {NoteASharp1, NoteBFlat1},
		35:  {NoteB1},
		36:  {NoteC2},
		37:  {NoteCSharp2, NoteDFlat2},
		38:  {NoteD2},
		39:  {NoteDSharp2, NoteEFlat2},
		40:  {NoteE2},
		41:  {NoteF2},
		42:  {NoteFSharp2, NoteGFlat2},
		43:  {NoteG2},
		44:  {NoteGSharp2, NoteAFlat2},
		45:  {NoteA2},
		46:  {NoteASharp2, NoteBFlat2},
		47:  {NoteB2},
		48:  {NoteC3},
		49:  {NoteCSharp3, NoteDFlat3},
		50:  {NoteD3},
		51:  {NoteDSharp3, NoteEFlat3},
		52:  {NoteE3},
		53:  {NoteF3},
		54:  {NoteFSharp3, NoteGFlat3},
		55:  {NoteG3},
		56:  {NoteGSharp3, NoteAFlat3},
		57:  {NoteA3},
		58:  {NoteASharp3, NoteBFlat3},
		59:  {NoteB3},
		60:  {NoteC4},
		61:  {NoteCSharp4, NoteDFlat4},
		62:  {NoteD4},
		63:  {NoteDSharp4, NoteEFlat4},
		64:  {NoteE4},
		65:  {NoteF4},
		66:  {NoteFSharp4, NoteGFlat4},
		67:  {NoteG4},
		68:  {NoteGSharp4, NoteAFlat4},
		69:  {NoteA4},
		70:  {NoteASharp4, NoteBFlat4},
		71:  {NoteB4},
		72:  {NoteC5},
		73:  {NoteCSharp5, NoteDFlat5},
		74:  {NoteD5},
		75:  {NoteDSharp5, NoteEFlat5},
		76:  {NoteE5},
		77:  {NoteF5},
		78:  {NoteFSharp5, NoteGFlat5},
		79:  {NoteG5},
		80:  {NoteGSharp5, NoteAFlat5},
		81:  {NoteA5},
		82:  {NoteASharp5, NoteBFlat5},
		83:  {NoteB5},
		84:  {NoteC6},
		85:  {NoteCSharp6, NoteDFlat6},
		86:  {NoteD6},
		87:  {NoteDSharp6, NoteEFlat6},
		88:  {NoteE6},
		89:  {NoteF6},
		90:  {NoteFSharp6, NoteGFlat6},
		91:  {NoteG6},
		92:  {NoteGSharp6, NoteAFlat6},
		93:  {NoteA6},
		94:  {NoteASharp6, NoteBFlat6},
		95:  {NoteB6},
		96:  {NoteC7},
		97:  {NoteCSharp7, NoteDFlat7},
		98:  {NoteD7},
		99:  {NoteDSharp7, NoteEFlat7},
		100: {NoteE7},
		101: {NoteF7},
		102: {NoteFSharp7, NoteGFlat7},
		103: {NoteG7},
		104: {NoteGSharp7, NoteAFlat7},
		105: {NoteA7},
		106: {NoteASharp7, NoteBFlat7},
		107: {NoteB7},
		108: {NoteC8},
		109: {NoteCSharp8, NoteDFlat8},
		110: {NoteD8},
		111: {NoteDSharp8, NoteEFlat8},
		112: {NoteE8},
		113: {NoteF8},
		114: {NoteFSharp8, NoteGFlat8},
		115: {NoteG8},
		116: {NoteGSharp8, NoteAFlat8},
		117: {NoteA8},
		118: {NoteASharp8, NoteBFlat8},
		119: {NoteB8},
		120: {NoteC9},
		121: {NoteCSharp9, NoteDFlat9},
		122: {NoteD9},
		123: {NoteDSharp9, NoteEFlat9},
		124: {NoteE9},
		125: {NoteF9},
		126: {NoteFSharp9, NoteGFlat9},
		127: {NoteG9},
	}
)

func (k MidiKey) String() string {
	switch k {
	case NoteC_1:
		return "NoteC_1"
	case NoteCSharp_1:
		return "NoteCSharp_1 / NoteDFlat_1"
	case NoteD_1:
		return "NoteD_1"
	case NoteDSharp_1:
		return "NoteDSharp_1 / NoteEFlat_1"
	case NoteE_1:
		return "NoteE_1"
	case NoteF_1:
		return "NoteF_1"
	case NoteFSharp_1:
		return "NoteFSharp_1 / NoteGFlat_1"
	case NoteG_1:
		return "NoteG_1"
	case NoteGSharp_1:
		return "NoteGSharp_1 / NoteAFlat_1"
	case NoteA_1:
		return "NoteA_1"
	case NoteASharp_1:
		return "NoteASharp_1 / NoteBFlat_1"
	case NoteB_1:
		return "NoteB_1"
	case NoteC0:
		return "NoteC0"
	case NoteCSharp0:
		return "NoteCSharp0 / NoteDFlat0"
	case NoteD0:
		return "NoteD0"
	case NoteDSharp0:
		return "NoteDSharp0 / NoteEFlat0"
	case NoteE0:
		return "NoteE0"
	case NoteF0:
		return "NoteF0"
	case NoteFSharp0:
		return "NoteFSharp0 / NoteGFlat0"
	case NoteG0:
		return "NoteG0"
	case NoteGSharp0:
		return "NoteGSharp0 / NoteAFlat0"
	case NoteA0:
		return "NoteA0"
	case NoteASharp0:
		return "NoteASharp0 / NoteBFlat0"
	case NoteB0:
		return "NoteB0"
	case NoteC1:
		return "NoteC1"
	case NoteCSharp1:
		return "NoteCSharp1 / NoteDFlat1"
	case NoteD1:
		return "NoteD1"
	case NoteDSharp1:
		return "NoteDSharp1 / NoteEFlat1"
	case NoteE1:
		return "NoteE1"
	case NoteF1:
		return "NoteF1"
	case NoteFSharp1:
		return "NoteFSharp1 / NoteGFlat1"
	case NoteG1:
		return "NoteG1"
	case NoteGSharp1:
		return "NoteGSharp1 / NoteAFlat1"
	case NoteA1:
		return "NoteA1"
	case NoteASharp1:
		return "NoteASharp1 / NoteBFlat1"
	case NoteB1:
		return "NoteB1"
	case NoteC2:
		return "NoteC2"
	case NoteCSharp2:
		return "NoteCSharp2 / NoteDFlat2"
	case NoteD2:
		return "NoteD2"
	case NoteDSharp2:
		return "NoteDSharp2 / NoteEFlat2"
	case NoteE2:
		return "NoteE2"
	case NoteF2:
		return "NoteF2"
	case NoteFSharp2:
		return "NoteFSharp2 / NoteGFlat2"
	case NoteG2:
		return "NoteG2"
	case NoteGSharp2:
		return "NoteGSharp2 / NoteAFlat2"
	case NoteA2:
		return "NoteA2"
	case NoteASharp2:
		return "NoteASharp2 / NoteBFlat2"
	case NoteB2:
		return "NoteB2"
	case NoteC3:
		return "NoteC3"
	case NoteCSharp3:
		return "NoteCSharp3 / NoteDFlat3"
	case NoteD3:
		return "NoteD3"
	case NoteDSharp3:
		return "NoteDSharp3 / NoteEFlat3"
	case NoteE3:
		return "NoteE3"
	case NoteF3:
		return "NoteF3"
	case NoteFSharp3:
		return "NoteFSharp3 / NoteGFlat3"
	case NoteG3:
		return "NoteG3"
	case NoteGSharp3:
		return "NoteGSharp3 / NoteAFlat3"
	case NoteA3:
		return "NoteA3"
	case NoteASharp3:
		return "NoteASharp3 / NoteBFlat3"
	case NoteB3:
		return "NoteB3"
	case NoteC4:
		return "NoteC4"
	case NoteCSharp4:
		return "NoteCSharp4 / NoteDFlat4"
	case NoteD4:
		return "NoteD4"
	case NoteDSharp4:
		return "NoteDSharp4 / NoteEFlat4"
	case NoteE4:
		return "NoteE4"
	case NoteF4:
		return "NoteF4"
	case NoteFSharp4:
		return "NoteFSharp4 / NoteGFlat4"
	case NoteG4:
		return "NoteG4"
	case NoteGSharp4:
		return "NoteGSharp4 / NoteAFlat4"
	case NoteA4:
		return "NoteA4"
	case NoteASharp4:
		return "NoteASharp4 / NoteBFlat4"
	case NoteB4:
		return "NoteB4"
	case NoteC5:
		return "NoteC5"
	case NoteCSharp5:
		return "NoteCSharp5 / NoteDFlat5"
	case NoteD5:
		return "NoteD5"
	case NoteDSharp5:
		return "NoteDSharp5 / NoteEFlat5"
	case NoteE5:
		return "NoteE5"
	case NoteF5:
		return "NoteF5"
	case NoteFSharp5:
		return "NoteFSharp5 / NoteGFlat5"
	case NoteG5:
		return "NoteG5"
	case NoteGSharp5:
		return "NoteGSharp5 / NoteAFlat5"
	case NoteA5:
		return "NoteA5"
	case NoteASharp5:
		return "NoteASharp5 / NoteBFlat5"
	case NoteB5:
		return "NoteB5"
	case NoteC6:
		return "NoteC6"
	case NoteCSharp6:
		return "NoteCSharp6 / NoteDFlat6"
	case NoteD6:
		return "NoteD6"
	case NoteDSharp6:
		return "NoteDSharp6 / NoteEFlat6"
	case NoteE6:
		return "NoteE6"
	case NoteF6:
		return "NoteF6"
	case NoteFSharp6:
		return "NoteFSharp6 / NoteGFlat6"
	case NoteG6:
		return "NoteG6"
	case NoteGSharp6:
		return "NoteGSharp6 / NoteAFlat6"
	case NoteA6:
		return "NoteA6"
	case NoteASharp6:
		return "NoteASharp6 / NoteBFlat6"
	case NoteB6:
		return "NoteB6"
	case NoteC7:
		return "NoteC7"
	case NoteCSharp7:
		return "NoteCSharp7 / NoteDFlat7"
	case NoteD7:
		return "NoteD7"
	case NoteDSharp7:
		return "NoteDSharp7 / NoteEFlat7"
	case NoteE7:
		return "NoteE7"
	case NoteF7:
		return "NoteF7"
	case NoteFSharp7:
		return "NoteFSharp7 / NoteGFlat7"
	case NoteG7:
		return "NoteG7"
	case NoteGSharp7:
		return "NoteGSharp7 / NoteAFlat7"
	case NoteA7:
		return "NoteA7"
	case NoteASharp7:
		return "NoteASharp7 / NoteBFlat7"
	case NoteB7:
		return "NoteB7"
	case NoteC8:
		return "NoteC8"
	case NoteCSharp8:
		return "NoteCSharp8 / NoteDFlat8"
	case NoteD8:
		return "NoteD8"
	case NoteDSharp8:
		return "NoteDSharp8 / NoteEFlat8"
	case NoteE8:
		return "NoteE8"
	case NoteF8:
		return "NoteF8"
	case NoteFSharp8:
		return "NoteFSharp8 / NoteGFlat8"
	case NoteG8:
		return "NoteG8"
	case NoteGSharp8:
		return "NoteGSharp8 / NoteAFlat8"
	case NoteA8:
		return "NoteA8"
	case NoteASharp8:
		return "NoteASharp8 / NoteBFlat8"
	case NoteB8:
		return "NoteB8"
	case NoteC9:
		return "NoteC9"
	case NoteCSharp9:
		return "NoteCSharp9 / NoteDFlat9"
	case NoteD9:
		return "NoteD9"
	case NoteDSharp9:
		return "NoteDSharp9 / NoteEFlat9"
	case NoteE9:
		return "NoteE9"
	case NoteF9:
		return "NoteF9"
	case NoteFSharp9:
		return "NoteFSharp9 / NoteGFlat9"
	case NoteG9:
		return "NoteG9"
	}
	panic(fmt.Sprintf("ui: invalid midi key: %d", k))
}
