// Code generated by glow (https://github.com/go-gl/glow). DO NOT EDIT.

package gl

import "unsafe"

type DebugProc func(
	source uint32,
	gltype uint32,
	id uint32,
	severity uint32,
	length int32,
	message string,
	userParam unsafe.Pointer)
